# Generated by Django 5.0.7 on 2024-08-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Dirección', models.CharField(max_length=100)),
                ('Provincia', models.CharField(max_length=100)),
            ],
        ),
    ]
