# Generated by Django 5.0.6 on 2024-07-12 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio_Unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Cantidad', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
    ]
