# Generated by Django 5.0.7 on 2024-08-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.IntegerField(default=0),
        ),
    ]
