# Generated by Django 5.0.6 on 2024-07-12 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Existencias', models.IntegerField()),
                ('Proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedore')),
            ],
        ),
    ]
