# Generated by Django 5.0.7 on 2024-08-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('existencias', models.IntegerField()),
                ('proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedore')),
            ],
        ),
    ]
