# Generated by Django 5.0.6 on 2024-07-12 04:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apertura_de_Caja', models.DateTimeField(default=datetime.datetime.now)),
                ('Saldo_Inicial', models.IntegerField()),
                ('Cierre_de_Caja', models.DateTimeField(default=datetime.datetime.now)),
                ('Saldo_Total', models.IntegerField()),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
