# Generated by Django 5.0.6 on 2024-07-27 05:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='Apertura_de_Caja',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Cierre_de_Caja',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Saldo_Inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Saldo_Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
